[nvfetcher]
fetch.github = "berberman/nvfetcher"
src.git = "https://github.com/berberman/nvfetcher"
src.branch = "master"

[crate2nix]
fetch.github = "kolloch/crate2nix"
src.git = "https://github.com/kolloch/crate2nix"

[nixpkgs]
src.git = "https://github.com/nixos/nixpkgs"
src.branch = "release-21.11"
fetch.tarball = "https://github.com/nixos/nixpkgs/archive/$ver.tar.gz"

[rust-overlay]
src.git = "https://github.com/oxalica/rust-overlay"
fetch.git = "https://github.com/oxalica/rust-overlay"

[holochain_branch_develop]
src.branch = "develop"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_9]
src.manual = "v0.0.9"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[lair_revision_v0_1_0]
src.manual = "v0.1.0"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_branch_main]
src.branch = "main"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_110]
src.manual = "holochain-0.0.110"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_7]
src.manual = "v0.0.7"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_115]
src.manual = "holochain-0.0.115"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_116]
src.manual = "holochain-0.0.116"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_117]
src.manual = "holochain-0.0.117"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_118]
src.manual = "holochain-0.0.118"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_119]
src.manual = "holochain-0.0.119"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_120]
src.manual = "holochain-0.0.120"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_121]
src.manual = "holochain-0.0.121"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_122]
src.manual = "holochain-0.0.122"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_123]
src.manual = "holochain-0.0.123"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_124]
src.manual = "holochain-0.0.124"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_125]
src.manual = "holochain-0.0.125"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_126]
src.manual = "holochain-0.0.126"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_103]
src.manual = "holochain-0.0.103"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_3]
src.manual = "v0.0.3"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_104]
src.manual = "holochain-0.0.104"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_4]
src.manual = "v0.0.4"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_105]
src.manual = "holochain-0.0.105"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_106]
src.manual = "holochain-0.0.106"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_107]
src.manual = "holochain-0.0.107"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_108]
src.manual = "holochain-0.0.108"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_109]
src.manual = "holochain-0.0.109"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_111]
src.manual = "holochain-0.0.111"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_8]
src.manual = "v0.0.8"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_112]
src.manual = "holochain-0.0.112"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_113]
src.manual = "holochain-0.0.113"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_114]
src.manual = "holochain-0.0.114"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_127]
src.manual = "holochain-0.0.127"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_128]
src.manual = "holochain-0.0.128"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_129]
src.manual = "holochain-0.0.129"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_130]
src.manual = "holochain-0.0.130"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_131]
src.manual = "holochain-0.0.131"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_132]
src.manual = "holochain-0.0.132"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_135]
src.manual = "holochain-0.0.135"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_136]
src.manual = "holochain-0.0.136"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_10]
src.manual = "v0.0.10"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_137]
src.manual = "holochain-0.0.137"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"
