[nvfetcher]
fetch.github = "berberman/nvfetcher"
src.git = "https://github.com/berberman/nvfetcher"
src.branch = "master"

[crate2nix]
fetch.github = "kolloch/crate2nix"
src.git = "https://github.com/kolloch/crate2nix"

[nixpkgs]
src.git = "https://github.com/nixos/nixpkgs"
src.branch = "release-22.11"
fetch.tarball = "https://github.com/nixos/nixpkgs/archive/$ver.tar.gz"

[rust-overlay]
src.git = "https://github.com/oxalica/rust-overlay"
fetch.git = "https://github.com/oxalica/rust-overlay"

[holochain_branch_develop]
src.branch = "develop"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_9]
src.manual = "v0.0.9"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[lair_revision_v0_1_0]
src.manual = "v0.1.0"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_branch_main]
src.branch = "main"
src.git = "https://github.com/holochain/holochain"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_110]
src.manual = "holochain-0.0.110"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_7]
src.manual = "v0.0.7"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_115]
src.manual = "holochain-0.0.115"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_116]
src.manual = "holochain-0.0.116"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_117]
src.manual = "holochain-0.0.117"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_118]
src.manual = "holochain-0.0.118"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_119]
src.manual = "holochain-0.0.119"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_120]
src.manual = "holochain-0.0.120"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_121]
src.manual = "holochain-0.0.121"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_122]
src.manual = "holochain-0.0.122"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_123]
src.manual = "holochain-0.0.123"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_124]
src.manual = "holochain-0.0.124"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_125]
src.manual = "holochain-0.0.125"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_126]
src.manual = "holochain-0.0.126"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_103]
src.manual = "holochain-0.0.103"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_3]
src.manual = "v0.0.3"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_104]
src.manual = "holochain-0.0.104"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_4]
src.manual = "v0.0.4"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_105]
src.manual = "holochain-0.0.105"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_106]
src.manual = "holochain-0.0.106"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_107]
src.manual = "holochain-0.0.107"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_108]
src.manual = "holochain-0.0.108"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_109]
src.manual = "holochain-0.0.109"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_111]
src.manual = "holochain-0.0.111"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_8]
src.manual = "v0.0.8"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_112]
src.manual = "holochain-0.0.112"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_113]
src.manual = "holochain-0.0.113"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_114]
src.manual = "holochain-0.0.114"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_127]
src.manual = "holochain-0.0.127"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_128]
src.manual = "holochain-0.0.128"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_129]
src.manual = "holochain-0.0.129"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_130]
src.manual = "holochain-0.0.130"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_131]
src.manual = "holochain-0.0.131"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_132]
src.manual = "holochain-0.0.132"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_135]
src.manual = "holochain-0.0.135"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_136]
src.manual = "holochain-0.0.136"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_10]
src.manual = "v0.0.10"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_137]
src.manual = "holochain-0.0.137"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_138]
src.manual = "holochain-0.0.138"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_139]
src.manual = "holochain-0.0.139"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_140]
src.manual = "holochain-0.0.140"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_141]
src.manual = "holochain-0.0.141"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_142]
src.manual = "holochain-0.0.142"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_143]
src.manual = "holochain-0.0.143"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_144]
src.manual = "holochain-0.0.144"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_145]
src.manual = "holochain-0.0.145"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_v0_0_11]
src.manual = "v0.0.11"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_146]
src.manual = "holochain-0.0.146"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_147]
src.manual = "holochain-0.0.147"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_148]
src.manual = "holochain-0.0.148"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_149]
src.manual = "holochain-0.0.149"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_150]
src.manual = "holochain-0.0.150"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_151]
src.manual = "holochain-0.0.151"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_152]
src.manual = "holochain-0.0.152"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_lair_keystore_api-v0_2_0]
src.manual = "lair_keystore_api-v0.2.0"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_153]
src.manual = "holochain-0.0.153"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_154]
src.manual = "holochain-0.0.154"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_155]
src.manual = "holochain-0.0.155"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_156]
src.manual = "holochain-0.0.156"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_157]
src.manual = "holochain-0.0.157"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_158]
src.manual = "holochain-0.0.158"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_159]
src.manual = "holochain-0.0.159"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_160]
src.manual = "holochain-0.0.160"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_161]
src.manual = "holochain-0.0.161"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_lair_keystore_api-v0_2_1]
src.manual = "lair_keystore_api-v0.2.1"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_162]
src.manual = "holochain-0.0.162"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_163]
src.manual = "holochain-0.0.163"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_164]
src.manual = "holochain-0.0.164"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_165]
src.manual = "holochain-0.0.165"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_166]
src.manual = "holochain-0.0.166"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_167]
src.manual = "holochain-0.0.167"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_168]
src.manual = "holochain-0.0.168"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_169]
src.manual = "holochain-0.0.169"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_170]
src.manual = "holochain-0.0.170"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_171]
src.manual = "holochain-0.0.171"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_172]
src.manual = "holochain-0.0.172"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_lair_keystore_api-v0_2_2]
src.manual = "lair_keystore_api-v0.2.2"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_173]
src.manual = "holochain-0.0.173"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_174]
src.manual = "holochain-0.0.174"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_0_175]
src.manual = "holochain-0.0.175"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_1_0-beta-rc_0]
src.manual = "holochain-0.1.0-beta-rc.0"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[lair_revision_lair_keystore_api-v0_2_3]
src.manual = "lair_keystore_api-v0.2.3"
fetch.git = "https://github.com/holochain/lair"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_1_0-beta-rc_1]
src.manual = "holochain-0.1.0-beta-rc.1"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_scaffolding_cli_revision_holochain_scaffolding_cli-v0_0_5-alpha_1]
src.manual = "holochain_scaffolding_cli-v0.0.5-alpha.1"
fetch.git = "https://github.com/holochain/scaffolding"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_2-alpha_1]
src.manual = "holochain_cli_launch-0.0.2-alpha.1"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_3-alpha_1]
src.manual = "holochain_cli_launch-0.0.3-alpha.1"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_3-alpha_2]
src.manual = "holochain_cli_launch-0.0.3-alpha.2"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_scaffolding_cli_revision_holochain_scaffolding_cli-v0_0_5-alpha_0]
src.manual = "holochain_scaffolding_cli-v0.0.5-alpha.0"
fetch.git = "https://github.com/holochain/scaffolding"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_1_0-beta-rc_2]
src.manual = "holochain-0.1.0-beta-rc.2"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_4-alpha_0]
src.manual = "holochain_cli_launch-0.0.4-alpha.0"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_scaffolding_cli_revision_holochain_scaffolding_cli-v0_0_5]
src.manual = "holochain_scaffolding_cli-v0.0.5"
fetch.git = "https://github.com/holochain/scaffolding"
cargo_lock = "Cargo.lock"

[holochain_scaffolding_cli_revision_holochain_scaffolding_cli-v0_0_6]
src.manual = "holochain_scaffolding_cli-v0.0.6"
fetch.git = "https://github.com/holochain/scaffolding"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_4-alpha_1]
src.manual = "holochain_cli_launch-0.0.4-alpha.1"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_1_0-beta-rc_3]
src.manual = "holochain-0.1.0-beta-rc.3"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_5]
src.manual = "holochain_cli_launch-0.0.5"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_revision_holochain-0_1_0-beta-rc_4]
src.manual = "holochain-0.1.0-beta-rc.4"
fetch.git = "https://github.com/holochain/holochain"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_6]
src.manual = "holochain_cli_launch-0.0.6"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_7]
src.manual = "holochain_cli_launch-0.0.7"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"

[holochain_cli_launch_revision_holochain_cli_launch-0_0_8]
src.manual = "holochain_cli_launch-0.0.8"
fetch.git = "https://github.com/holochain/launcher"
cargo_lock = "Cargo.lock"
