---
name: Build
"on":
  pull_request: ~
concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: false
jobs:
  crate-tests:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        cachixName:
          - holochain-ci
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        if: "${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}"
        with:
          name: "${{ matrix.cachixName }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Set NIX_PATH (FIXME)
        if: "${{ matrix.platform == 'macos-latest' }}"
        run: "echo NIX_PATH=nixpkgs=$(nix eval --impure --raw --expr '(import ./nix/nvfetcher/sources.nix {}).nixpkgs.src') >> $GITHUB_ENV"
      - name: Run cargo tests
        run: "nix-shell --pure --run \"cargo test\""
  holochain-binaries:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        nixAttribute:
          - main
          - develop
          - v0_0_120
          - v0_0_121
          - v0_0_122
          - v0_0_123
          - v0_0_124
          - v0_0_125
          - v0_0_126
          - v0_0_127
        nurRepo:
          - holochain-nixpkgs
        cachixName:
          - holochain-ci
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: false
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Show nixpkgs version
        run: "nix-instantiate --eval -E '(import (import ./nix/nvfetcher/sources.nix {}).nixpkgs.src {}).lib.version'"
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        if: "${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}"
        with:
          name: "${{ matrix.cachixName }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivations
        env:
          nix_attribute: "${{ matrix.nixAttribute }}"
        run: "nix build -f . \"packages.holochain.holochainAllBinariesWithDeps.${nix_attribute}\" --extra-experimental-features nix-command"
  packages:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
        nixAttribute:
          - update-holochain-versions
          - holochain-nixpkgs-util
        cachixName:
          - holochain-ci
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.5
      - name: Install nix
        uses: cachix/install-nix-action@v16
      - name: Show nixpkgs version
        run: "nix-instantiate --eval -E '(import (import ./nix/nvfetcher/sources.nix {}).nixpkgs.src {}).lib.version'"
      - name: Setup cachix
        uses: cachix/cachix-action@v10
        if: "${{ matrix.cachixName != '<YOUR_CACHIX_NAME>' }}"
        with:
          name: "${{ matrix.cachixName }}"
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build derivations
        env:
          nix_attribute: "${{ matrix.nixAttribute }}"
        run: "nix build -f . \"packages.${nix_attribute}\" --extra-experimental-features nix-command"
  all-jobs-succeed:
    runs-on: ubuntu-latest
    needs:
      - crate-tests
      - holochain-binaries
      - packages
    steps:
      - name: all-jobs-succeed
        run: ":"
